utils/logger.py

유틸에 로깅 기능 추가
Closes #9 
utils/logger.py에 로깅 추가
임포트 이후에
logger = get_logger(__name__)로 실행

feat: logger추가

---

.gitignore
backend/text_generator/core/main.py
config.yaml

텍스트 생성 코드 베이스라인 추가
Related to #6 
backend/text_generator/core/main.py 추가
config.yaml input값 수정
backend/data/output에 .html 파일 생성됨

feat: 텍스트 생성 코드 베이스라인 추가(#6)

---

.gitignore
backend/text_generator/core/text_generator.py
backend/text_generator/text_generator_main.py

GPT temperature를 0.6에서 0.9로 수정
Related to #6 
ubuntu/2025-GEO-Project/backend/text_generator/core/text_generator.py

feat: temperature 수정 (#6)

---

backend/main2.py
backend/page_generator/page_generator_main.py
backend/text_generator/text_generator_main.py
config.yaml

- fastAPI 없이 파이썬으로만 이루어진 테스트 전용 main2.py 생성
- config.yaml에서 link 제거
Related to #6 
- 2025-GEO-Project/backend/main2.py
- 2025-GEO-Project/config.yaml
[250710 00:35:56] [INFO] [__main__] - ✅ config.yaml 로드 완료
[250710 00:35:56] [INFO] [__main__] - 🛠️ 텍스트 상세페이지 생성 시작
[250710 00:35:56] [INFO] [backend.text_generator.core.text_generator] - 🛠️ OpenAI 요청 시작
[250710 00:36:20] [INFO] [backend.text_generator.core.text_generator] - ✅ OpenAI API 응답 수신 완료
[250710 00:36:20] [INFO] [backend.text_generator.core.text_generator] - ✅ 코드 마크다운 블록 제거 완료
[250710 00:36:20] [DEBUG] [backend.text_generator.text_generator_main] - 🛠️ 파일명 생성 시작
[250710 00:36:20] [INFO] [backend.text_generator.text_generator_main] - ✅ HTML 상세페이지 저장 완료: backend/data/output/draft_20250710_093620_439.html
[250710 00:36:20] [INFO] …

feat: 테스트용 main2.py 생성 (#6)

---

backend/image_generator/core/background_handler.py
backend/image_generator/core/image_loader.py
backend/image_generator/core/prompt_builder.py
backend/image_generator/image_generator_main.py
backend/models/model_handler.py

ipa+sdxl기반 이미지와 프롬프트로 제품에 어울리는 배경/제품을 사용하는 사람 이미지 생성기능 구현
Related to #11 
modified:   backend/image_generator/core/background_handler.py
modified:   backend/image_generator/core/prompt_builder.py
modified:   backend/image_generator/image_generator_main.py
modified:   backend/models/model_handler.py
```bash
(ys) user@sprint-ai01-team1:~/2025-GEO-Project$ python image_test.py
[250710 02:30:24] [DEBUG] [__main__] - 🛠️ config.yaml 로드 시작
[250710 02:30:24] [INFO] [__main__] - ✅ config.yaml 로드 완료
[250710 02:30:24] [DEBUG] [__main__] - 🛠️ 모델 다운로드 및 로드 시작
[250710 02:30:24] [INFO] [backend.models.model_handler] - ✅ 모델 stabilityai/sdxl-turbo이(가) 이미 /home/user/2025-GEO-Project/backend/models에 존재
[250710 02:30:25] [INFO] [backend.models.model_handler] - ✅ GPU를 사용하여 모델을 로드
Loading pipeline …
```

feat: ipa+sdxl기반 이미지와 프롬프트로 제품에 어울리는 배경/제품을 사용하는 사람 이미지 생성기능 구현 (#11)

---

backend/image_generator/core/background_handler.py
backend/image_generator/core/prompt_builder.py
backend/image_generator/image_generator_main.py

ipa+sdxl기반의 이미지 생성기 시험 구현 완료
현재로서는 가장 괜찮은 퀄리티로 생성됨
Related to #11
modified:   backend/image_generator/core/background_handler.py
modified:   backend/image_generator/core/prompt_builder.py
modified:   backend/image_generator/image_generator_main.py
```bash
(ys) user@sprint-ai01-team1:~/2025-GEO-Project$ python image_test.py
[250710 07:27:48] [DEBUG] [__main__] - 🛠️ config.yaml 로드 시작
[250710 07:27:48] [INFO] [__main__] - ✅ config.yaml 로드 완료
[250710 07:27:48] [DEBUG] [__main__] - 🛠️ 이미지 생성기 시작
[250710 07:27:48] [DEBUG] [backend.image_generator.image_generator_main] - 🛠️ 이미지 로드 시작
[250710 07:27:48] [DEBUG] [backend.image_generator.core.image_loader] - 🛠️ ImageLoader 초기화 시작
[250710 07:27:48] [INFO] [backend.image_generator.core.image_loader] - ✅ ImageLoader 초기화 완료
[250710 07:27:48] [DEBUG] …
```

fix: 이미지 생성기 통합 및 시험 구현 완료

---

backend/competitor_analysis/api/competitor_router.py
backend/competitor_analysis/core/competitor_main.py
backend/competitor_analysis/schemas/input_schema.py
config.yaml
utils/config.py

FastAPI용 api 라우터 코드 구현 및 config.py 코드 구현
Related to #3
2025-GEO-Project/backend/competitor_analysis/api/competitor_router.py
2025-GEO-Project/utils/config.py
2025-GEO-Project/config.yaml

feat: api 관련 코드 추가 / config.py 함수 구현 / config.yaml에 db설정 관련 데이터 추가

---

config.yaml

- config.yaml에 빠진 css_type 추가
Related to #6 
2025-GEO-Project/config.yaml
```
[250711 02:44:48] [DEBUG] [utils.config] - 🛠️ config.yaml 로딩 시작: /home/spai0103/2025-GEO-Project/config.yaml
[250711 02:44:48] [INFO] [utils.config] - ✅ config.yaml 로딩 성공
[250711 02:44:48] [INFO] [__main__] - 🛠️ 텍스트 상세페이지 생성 시작
[250711 02:44:48] [INFO] [backend.text_generator.core.text_generator] - 🛠️ OpenAI 요청 시작
[250711 02:45:25] [INFO] [backend.text_generator.core.text_generator] - ✅ OpenAI API 응답 수신 완료
[250711 02:45:25] [INFO] [backend.text_generator.core.text_generator] - ✅ 코드 마크다운 블록 제거 완료
[250711 02:45:25] [DEBUG] [backend.text_generator.text_generator_main] - 🛠️ 파일명 생성 시작
[250711 02:45:25] [INFO] [backend.text_generator.text_generator_main] - ✅ HTML 상세페이지 저장 완료: …
```

feat: config.yaml에 빠진 항목 추가 (#6)

---

backend/competitor_analysis/core/competitor_main.py

리턴을 pydantic에서 딕셔너리로 변경
Related to #3
CompetitorOutput(differences=differences).model_dump()

fix: 리턴을 pydantic에서 딕셔너리로 변경

---

backend/competitor_analysis/core/competitor_main.py

리턴을 다시 스키마로 변경
Related to #3
return CompetitorOutput(differences=differences)

fix(return): 리턴을 다시 스키마로 변경

---

backend/router/router.py
config.yaml

라우터 허물 구현
Related to #3
input을 받은 후 처리 로직 라우터 구현

feat(router): 진짜 기능 테스트 안해보고 실행만 되는걸 확인하고 올립니다

---

.gitignore
backend/image_generator/image_generator_main.py
backend/main.py

backend/main의 이미지라우터 삭제함
modified:   backend/main.py

fix: 이미지라우터 삭제로 인해 backend/main의 이미지라우터  

---

backend/image_generator/background_handler.py
backend/image_generator/hash_utils.py
backend/image_generator/image_generator_main.py
backend/image_generator/prompt_builder.py
backend/models/model_handler.py
image_test.py
requirements.txt

Part of #11 
backend/image_generator/hash_utils.py
backend/image_generator/
```bash
[250721 01:45:10] [DEBUG] [__main__] - 🛠️ 테스트 시작
[250721 01:45:10] [DEBUG] [__main__] - 🛠️ config.yaml 로드 시작
[250721 01:45:10] [INFO] [__main__] - ✅ config.yaml 로드 완료
[250721 01:45:10] [DEBUG] [__main__] - 🛠️ 이미지 생성기 시작
[250721 01:45:10] [DEBUG] [backend.image_generator.image_generator_main] - 🛠️ 이미지 생성기 파이프라인 초기화 시작
[250721 01:45:10] [DEBUG] [backend.image_generator.image_loader] - 🛠️ ImageLoader 초기화 시작
[250721 01:45:10] [INFO] [backend.image_generator.image_loader] - ✅ ImageLoader 초기화 완료
[250721 01:45:10] [DEBUG] [backend.image_generator.background_handler] - 🛠️ BackgroundHandler 초기화 시작
[250721 01:45:10] [INFO] [backend.image_generator.background_handler] - ✅ BackgroundHandler 초기화 완료
[250721 01:45:10] …
```

feat&fix: 캐시 기반 이전 결과 불러오기 기능 구현 및 이미지 파이프라인 정리 (#11)

---

backend/router/router.py

라우터 엔드포인트 변경 및 app 객체 삭제, summary와 description 추가
Related to #3
fix(router): 엔드포인트 변경
refactor(Swagger): summary와 description 추가
refactor(app): app선언 삭제

refactor: 라우터 엔드포인트 변경 및 app 객체 삭제

---

backend/page_generator/page_generator_main.py
backend/text_generator/cleaner.py
backend/text_generator/text_generator.py
config.yaml

허깅페이스 상세페이지 생성 시 후처리 보완
Related to #6 
2025-GEO-Project/backend/text_generator

feat: 허깅페이스 상세페이지 생성 시 후처리 보완 (#6)

---

backend/router/router.py
config.yaml

라우터 수정 및 config 수정
Related to #42
[fix(output): 아웃풋 라우터 로직 순서 수정 < 인자로 session_id를 안받는다는 가정]
[remove(config): config.yaml에서 세팅 관련 데이터 삭제]

fix(output): 아웃풋 라우터 로직 순서 수정 < 인자로 session_id를 안받는다는 가정

---

backend/router/router.py

페이지 생성에 인자 세션 ID 삭제
Related to #42
fix(page): 페이지 생성에 인자 세션 ID 삭제

fix(page): 페이지 생성에 인자 세션 ID 삭제

---

backend/image_generator/background_handler.py
backend/image_generator/hash_utils.py
backend/image_generator/image_generator_main.py
backend/image_generator/image_loader.py
backend/image_generator/prompt_builder.py
backend/models/model_handler.py

ip-adapter이후 vram사용량을 줄이기위한 `enable_attention_slicing()`이 문제였음. 제거하여 수정
이미지생성기 폴더 내부 파일 리팩토링 및 정리
Related to #11
backend/models/model_handler.py
backend/image_generator/
```bash
(ys) user@sprint-ai01-team1:/home/ubuntu/2025-GEO-Project$ python image_test.py
✅ 모델 저장 경로 설정: /home/ubuntu/2025-GEO-Project/backend/models
[250722 06:50:58] [DEBUG] [__main__] - 🛠️ 테스트 시작
[250722 06:50:58] [DEBUG] [__main__] - 🛠️ config.yaml 로드 시작
[250722 06:50:58] [INFO] [__main__] - ✅ config.yaml 로드 완료
[250722 06:50:58] [DEBUG] [__main__] - 🛠️ 이미지 생성기 시작
[250722 06:50:58] [DEBUG] [backend.image_generator.image_generator_main] - 🛠️ 이미지 생성기 파이프라인 초기화 시작
[250722 06:50:58] [DEBUG] [backend.image_generator.image_loader] - 🛠️ ImageLoader 초기화 시작
[250722 06:50:58] [INFO] [backend.image_generator.image_loader] - ✅ …
```

fix&refactor: 이미지 생성기 ip-adapter관련 오류 수정 및 리팩토링 (#11)

---

backend/competitor_analysis/local_run.py
config.yaml

자동 크롤링 주기 24시간으로 변경
Related to #3
fix: 자동 크롤링 주기 24시간으로 변경
fix(pw): config.yaml에 DB password 삭제

fix: 자동 크롤링 주기 24시간으로 변경

---

README.md

리드미 수정중
Related to #66
README.md

fix: 리드미 수정 (#66)

---

requirements.txt

requirements 수정
Related to #3
fix(pip): requirements 수정

fix(pip): requirements 수정

---

backend/input_handler/core/image_composer.py
backend/input_handler/core/input_main.py
backend/main.py
config.yaml
frontend/pages/image_compose.py
frontend/pages/result.py
run.py

상품 배경 이미지 생성
상품 배경 이미지 생성
쓸모 없어진 mask 관련 코드 삭제

Feat:상품 배경 이미지 생성

---

.gitignore
README.md

협업일지 및 보고서 링크 추가
움짤 등록
Related to #66
feat(link): 협업일지 및 보고서 링크 추가
feat(gif): 움짤 등록

feat(link): 협업일지 및 보고서 링크 추가

---

README.md

보고서 링크 및 PPT 링크 수정
Related to #66 
보고서 링크 및 PPT 링크 수정

docs: 보고서 링크 및 PPT 링크 수정
